server:
  port: 8087
dubbo:
  application:
    name: dubbo-consumer
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    #启动应用时是否检查注册中心上有没有依赖的服务，默认true
    check: false
  protocol:
     #协议及端口
      name: dubbo
      port: 20880
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1727883570zlm
    url: jdbc:mysql://localhost:3306/dubbo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC&useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.guigu.pojo